#!/usr/bin/env ruby

day = ARGV.first
part = ARGV[1] || 1

puts "Testing solution for day #{day}, part #{part}"

suffix = part == 1 ? '' : '_2'

Dir.chdir(__dir__) do
  example_file =
    if File.exist?("#{day}/example#{suffix}")
      "#{day}/example#{suffix}"
    else
      "#{day}/example"
    end

  got = `cat #{example_file} | bundle exec #{day}/solve#{suffix}`
  want = File.read("#{day}/example_solution#{suffix}")
  if got.chomp == want.chomp
    puts 'OK'
  else
    puts 'FAILED'
    puts
    puts "Got: #{got}"
    puts "Want: #{want}"
  end
end
