#!/usr/bin/env ruby

def distances(levels) = levels.each_cons(2).map { _2 - _1 }
def same_direction?(distances) = distances.all?(&:positive?) || distances.all?(&:negative?)
def safe_distance?(distances) = distances.map(&:abs).all? { (1..3).include?(_1) }

reports = ARGF.read.split("\n").map { _1.split.map(&:to_i) }

puts reports
  .map { distances(_1) }
  .select { same_direction?(_1) && safe_distance?(_1) }
  .count
